#
# $Id$
#
# $Log$
# Revision 1.1  1995/01/25 17:10:49  jba
# Initial version
#
#

EPICS = ../../../..
include Target.include
include $(EPICS)/config/CONFIG_EXTENSIONS


DEPLIBS = $(EPICS_BASE_LIB)/libca.a  $(EPICS_BASE_LIB)/libCom.a

USR_LDLIBS = -lca -lCom

SRCS.c = ../camonitor.c

PROD = camonitor

include $(EPICS)/config/RULES.Unix

