#
# $Id$
#
# $Log$
# Revision 1.2  1997/02/12 18:04:41  jbk
# added new program to monitor pv and call script when value changes
#
# Revision 1.1  1995/01/25 17:10:49  jba
# Initial version
#
#

EPICS = ../../../..
include Target.include
include $(EPICS)/config/CONFIG_EXTENSIONS


DEPLIBS = $(EPICS_BASE_LIB)/libca.a  $(EPICS_BASE_LIB)/libCom.a

USR_LDLIBS = -lca -lCom

SRCS.c = ../camonitor.c ../camonitorpv.c

PROD = camonitor camonitorpv

include $(EPICS)/config/RULES.Unix

